### ISSUE TITLE
Map filter prop doesn't update when option selected (work on dynamic filtering!)

### ISSUE THREAD

**Issue by 20wontons** [ggarcia453/AroundtheWorldRadio#1]
References:
https://stackoverflow.com/questions/65763931/react-leaflet-update-map-center
https://stackoverflow.com/questions/64665827/react-leaflet-center-attribute-does-not-change-when-the-center-state-changes
https://stackoverflow.com/questions/16148598/leaflet-update-geojson-filter

**Comment by ggarcia453** [comment]
https://plainenglish.io/blog/how-to-implement-a-search-bar-in-react-js

**Comment by 20wontons** [comment]
"Note: dynamically changing the filter option will have effect only on newly added data. It will not re-evaluate already included features."
https://leafletjs.com/reference.html#geojson

**Comment by 20wontons** [comment]
fixed by adding `key={props.frequency}` to the props of `<GeoJSON/>` component tag
Reference: https://stackoverflow.com/questions/44155385/rendering-geojson-with-react-leaflet
